# Gopkg.toml

[[constraint]]
  name = "github.com/go-sql-driver/mysql"
  version = "1.2.0"

[[constraint]]
  name = "github.com/go-chi/chi"
  version = "3.3.2"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"

[prune]
  go-tests = true
  unused-packages = true